SIMULATION_MODE = False

GPS_ENABLED = True
IMU_ENABLED = True
DISTANCE_SENSOR_ENABLED = True

GPS_PORT = "/dev/serial0"
GPS_BAUDRATE = 9600

HC_SR04_TRIGGER_PIN = 23
HC_SR04_ECHO_PIN = 24

MPU6050_ADDRESS = 0x68